### ISSUE TITLE
implement deserialize(T::Type, jsonstring::String)

### ISSUE THREAD

**Issue by stevengj** [JuliaIO/JSON.jl#39]
Similar to Go's [Unmarshal](http://golang.org/pkg/encoding/json/#Unmarshal), as suggested in #38.

**Comment by MrTomWhite** [comment]
Has there been any progress on this issue?

**Comment by kmsquire** [comment]
I would guess that it has fallen off of people's radar.  Care to take a crack at it?

**Comment by MrTomWhite** [comment]
I'll write up a pr soon. Thanks!

**Comment by tlycken** [comment]
I have a local implementation of this. It's really simple:

```
using JSON

deserialize{T}(::Type{T}, json::AbstractString) = deserialize(T, JSON.parse(json))
deserialize{T}(::Type{T}, json::Dict) = T(flatten([deserialize(T, f, json) for f in fieldnames(T)])...)
deserialize{Tf}(::Type{Tf}, field::AbstractString, json::Dict) = deserialize(Tf, json[field])
deserialize{Tf<:Nullable}(::Type{Tf}, field::AbstractString, json::Dict) = haskey(json, field) ? deserialize(Tf, json[field]) : Tf()
deserialize{T}(::Type{T}, field::Symbol, json::Dict) = deserialize(fieldtype(T,field), string(field), json)
deserialize{T<:Integer}(::Type{T}, i::Integer) = T(i)
deserialize{T<:Integer}(::Type{T}, i::AbstractString) = parse(T, i)
deserialize{T<:AbstractFloat}(::Type{T}, i::AbstractFloat) = T(i)
deserialize{T<:AbstractFloat}(::Type{T}, i::AbstractString) = parse(T, i)
deserialize{T}(::Type{Nullable{T}}, x) = deserialize(T, x)

flatten{T<:Array}(A::Array{T,1}) = vcat(flatten(A)...)
flatten{T}(A::Array{T,1}) = vcat(A...)
flatten(A) = A
```

This works for a couple of cases that I could come up with, including making fields optional if their types are `Nullable`:

```
using Base.Test
input = "{ \"bar\": { \"baz\": 17 }, \"foo\": 3.14 }"

immutable Bar
    baz::Int
end

immutable Foo
    bar::Bar
end

immutable Baz
    foo::Nullable{Float64}
    bar::Bar
end

immutable Qux
    baz::Nullable{UTF8String}
    bar::Bar
end

@test deserialize(Foo, input) == Foo(Bar(17))
@test deserialize(Baz, input) == Baz(Nullable(3.14), Bar(17))
@test deserialize(Qux, input) == Qux(Nullable{UTF8String}(),Bar(17))
```

Of course, it needs a little documentation, and I'd probably want to use a `flatten` from somewhere rather than roll my own, but I can take a look at that when I file the actual PR (which won't be until this weekend, at the earliest).

**Comment by leethargo** [comment]
@tlycken: I wanted to use your `deserialize` for a type that uses an array as a field, e.g.
```julia
immutable MyColl
    n::Int
    x::Vector{Float64}
end
```
which didn't work, because `deserialize` could not dispatch on `Array` at all. So I added this method:
```julia
deserialize{T,N}(::Type{Array{T,N}}, A::Array{Any,N}) = T[deserialize(T, a) for a in A]
```
that I hoped was correct (how do I specify the shape of the result?). Unfortunately, the `x::Vector` was broken up by `flatten`, so that `deserialize` tried to build a `MyColl` from `::Int, ::Float64, Float64...` which failed.

By removing all methods of `flatten` but the identity, I got it working on my user types, but I'm sure that they are there for a reason.

**Comment by josefsachsconning** [comment]
@tlycken Thanks for that.  In v0.5, after changing UTF8String to String, I get the following.
```
julia> deserialize(Qux, input)
ERROR: MethodError: Cannot `convert` an object of type Nullable{Any} to an object of type Bar
This may have arisen from a call to the constructor Bar(...),
since type constructors fall back to convert methods.
 in Qux(::Nullable{Any}, ::Nullable{Any}) at /home/sachs/lib/julia/JsonDeserialize.jl/test/runtests.jl:18
 in deserialize(::Type{Qux}, ::Dict{String,Any}) at /home/sachs/lib/julia/JsonDeserialize.jl/src/JsonDeserialize.jl:6
 in deserialize(::Type{Qux}, ::String) at /home/sachs/lib/julia/JsonDeserialize.jl/src/JsonDeserialize.jl:5
```
Any explanation, and hopefully a workaround?

**Comment by tlycken** [comment]
@josefsachsconning no, unfortunately not at this time. I haven't worked actively with Julia for over half a year now... :(

**Comment by lwabeke** [comment]
Based on discussion, I rather created a seperate Unmarshal package, with the hope that at some point it can be made to work for other data formats as well, not just be limited to JSON.
Waiting for it to be included in METADATA:
https://github.com/lwabeke/METADATA.jl/compare/pull-request/c487d969

Pkg.clone(https://github.com/lwabeke/Unmarshal.jl.git)

**Comment by TotalVerb** [comment]
Thanks @lwabeke!
